export default {
  "ACCT": "Accounting",
  "ACTL": "Actuarial Studies",
  "AERO": "Aerospace Engineering",
  "ANAT": "Anatomy",
  "ANZG": "Public Administration (ANZSOG)",
  "ARCH": "Architecture",
  "ARTS": "Arts",
  "ASIA": "Asian Studies",
  "ATSI": "Nura Gili (Indigenous Programs)",
  "AUST": "Australian Studies",
  "AVEN": "Aviation",
  "AVIA": "Aviation",
  "AVIF": "Aviation",
  "AVIG": "Aviation",
  "BABS": "Biotechnology & Biomolecular Sciences",
  "BEES": "Biological, Earth and Environmental Sciences",
  "BEIL": "BE Interdisciplinary Learning",
  "BENV": "Built Environment",
  "BINF": "Bioinformatics",
  "BIOC": "Biochemistry",
  "BIOM": "Biomedical Engineering",
  "BIOS": "Biological Science",
  "BIOT": "Biotechnology",
  "BLDG": "Building",
  "CDEV": "Career Development",
  "CEIC": "Chemical Engineering and Industrial Chemistry",
  "CHEM": "Chemistry",
  "CHEN": "Chemical Engineering",
  "CLIM": "Climate Science",
  "CODE": "Computational Design",
  "COMD": "Comparative Development",
  "COMM": "Commerce",
  "COMP": "Computer Science",
  "CONS": "Construction Management",
  "CRIM": "Criminology",
  "CRTV": "Creative Practice",
  "CVEN": "Civil and Environmental Engineering",
  "DATA": "Data Science",
  "DESN": "Design Next",
  "DPBS": "Global Diploma – Business",
  "DPGE": "Global Diploma – General Education",
  "DPST": "Global Diploma – STEM",
  "ECON": "Economics",
  "EDST": "Education",
  "ELEC": "Electrical Engineering",
  "ENGG": "Engineering Interdisciplinary",
  "ENGL": "English",
  "ENVS": "Environmental Studies",
  "EXCH": "Registrar’s Division",
  "FINS": "Finance",
  "FNDN": "New South Global – Foundation Studies",
  "FOOD": "Food Technology",
  "GENC": "Business General Education",
  "GENE": "Engineering General Education",
  "GENL": "Law General Education",
  "GENM": "Medicine General Education",
  "GENS": "Science General Education",
  "GENY": "Student Academic and Career Success – GE",
  "GEOL": "Geology",
  "GEOS": "Geoscience",
  "GMAT": "Surveying and Spatial Information Systems",
  "GSBE": "Architecture",
  "GSOE": "Grad School of Engineering",
  "HDAT": "Health Data Science",
  "HESC": "Health and Exercise Science",
  "HIST": "History",
  "HPSC": "History and Philosophy of Science",
  "HUML": "Humanities and Languages",
  "HUMS": "Arts Administration",
  "IDES": "Industrial Design",
  "IEST": "Environmental Studies",
  "INFS": "Information Systems",
  "INST": "International Studies",
  "INTA": "Interior Architecture",
  "INTD": "Interdisciplinary Studies",
  "JURD": "Juris Doctor",
  "LAND": "Landscape Architecture",
  "LAWS": "Law",
  "LING": "Linguistics",
  "MANF": "Manufacturing Engineering",
  "MARK": "Marketing",
  "MATH": "Mathematics",
  "MATS": "Materials Science and Engineering",
  "MBAX": "Management",
  "MDCN": "Medicine",
  "MDIA": "Media",
  "MECH": "Mechanical Engineering",
  "MERE": "Minerals and Energy Resources Engineering",
  "MFAC": "Medicine",
  "MFIN": "Master of Finance Courses",
  "MGMT": "Organisation and Management – Commerce & Economics",
  "MICR": "Microbiology",
  "MINE": "Mining Engineering",
  "MMAN": "Mechanical & Manufacturing Engineering",
  "MNGT": "Management",
  "MODL": "Modern Language Studies",
  "MSCI": "Marine Science",
  "MTRN": "Mechatronic Engineering",
  "MUSC": "Music and Music Education",
  "NANO": "Nanotechnology",
  "NCHR": "HIV Social Research",
  "NEUR": "Neuroscience",
  "OBST": "Obstetrics and Gynaecology – RHW",
  "OPTM": "Optometry",
  "PAED": "Paediatrics",
  "PATH": "Pathology",
  "PHAR": "Pharmacology",
  "PHCM": "Public Health and Community Medicine",
  "PHIL": "Philosophy",
  "PHOP": "Public Health Offshore Programs",
  "PHSL": "Physiology",
  "PHTN": "Photonics",
  "PHYS": "Physics",
  "PLAN": "Planning and Urban Development",
  "PLTX": "Practical Legal Training Program",
  "POLS": "Politics and International Relations",
  "POLY": "Polymer Science",
  "PPEC": "Philosophy, Politics and Economics",
  "PSCY": "Psychiatry – PH/POW",
  "PSYC": "Psychology",
  "PTRL": "Petroleum Engineering",
  "REGZ": "Registrar’s Division",
  "REST": "Real Estate",
  "RISK": "Risk Management",
  "SCIF": "Faculty of Science",
  "SENG": "Software Engineering",
  "SLSP": "Social Science and Policy",
  "SOCA": "Sociology and Anthropology",
  "SOCF": "Social Work",
  "SOCW": "Social Work",
  "SOLA": "Photovoltaics and Solar Energy",
  "SOMS": "Medical Science",
  "SOSS": "Social Sciences",
  "SPRC": "Social Policy",
  "SRAP": "Social Research and Policy",
  "STAM": "Arts and Media",
  "SURG": "Surgery – PH/POW",
  "SUSD": "Sustainable Development",
  "SWCH": "Women & Children’s Health",
  "TABL": "Taxation and Business Law",
  "TELE": "Telecommunications",
  "UDES": "Urban Development Studies",
  "VISN": "Vision Science",
  "WOMS": "Womens Studies",
  "YENG": "Arizona State University Engineering",
  "YMED": "Arizona State University Medicine",
  "ADAD": "Art and Design",
  "DART": "Domain Art",
  "DDES": "Domain Design",
  "SAHT": "Art History",
  "SART": "Art",
  "SDES": "Design Studies",
  "SOMA": "Media Arts",
  "YCAN": "ASU Canberra",
  "ZBUS": "Business",
  "ZEIT": "Engineering & Information Technology",
  "ZGEN": "University College General Education",
  "ZHSS": "Humanities & Social Sciences",
  "ZINT": "University College (Interdisciplinary)",
  "ZPEM": "Physical, Environmental & Mathematical Sciences"
};