version: "3.7"
services:
  server:
    container_name: notangles_server
    # restart: always
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - database
    links:
      - database
  database:
    container_name: notangles_database
    # restart: always
    image: mongo:latest
    volumes:
      - /data/db:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: notangles
      MONGO_INITDB_ROOT_PASSWORD: notangles
      MONGO_INITDB_DATABASE: 2019